### ISSUE TITLE
Client disconnects when password contains extended ASCII

### ISSUE THREAD

**Issue by txtsd** [Illarion-eV/Illarion-Java#132]
With a password that contains extended ASCII (eg: `»ø¦ÿÜ¿öÏàäÿí£Ê·ÌÃµ¾µ`), I'm able to login to the website just fine.

I'm also able to retrieve my list of characters in the client fine.

Although, after selecting a character, the client disconnects and goes back to the login screen.

This is what the log shows:

```
ERROR - 2022-01-27 22:41:39,152 - [LWJGL Application]: Book ID: 417 not found. File goodregent.book.xml is missing in the resources.
WARN  - 2022-01-27 22:42:05,510 - [LWJGL Application]: Changing the locale will not effect ALL loaded resource bundles. TextRenderer should work now tho :)
WARN  - 2022-01-27 22:42:09,660 - [pool-7-thread-1]: Disconnect received: Connection was stopped by the server.
Reason: The password is wrong.
ERROR - 2022-01-27 22:42:09,681 - [Illarion input thread]: The connection to the server is not working anymore.
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at illarion.client.net.Receiver.receiveData(Receiver.java:424)
	at illarion.client.net.Receiver.run(Receiver.java:274)
WARN  - 2022-01-27 22:42:09,700 - [Illarion input thread]: Disconnect received: A technical problem in Receiver thread has occurred. Check logfiles for details.
ERROR - 2022-01-27 22:42:09,767 - [pool-6-thread-1]: Connection failure: Broken pipe

```

I was able to get ingame after changing my password to one that doesn't have extended ASCII in it.

In this age of password managers, it's very important to be able to handle any kind of password.

(I'm not sure if the problem is in the client or the server, so feel free to move the issue to the server repo if the issue stems from there.)

**Comment by estralis** [comment]
https://illarion.org/mantis/view.php?id=6242
https://illarion.org/mantis/view.php?id=6242

**Comment by txtsd** [comment]
> https://illarion.org/mantis/view.php?id=6242 https://illarion.org/mantis/view.php?id=8936

Access Denied.

:(

**Comment by r-lodahl** [comment]
The results of the PHP crypt() function and of the clients encrypting function differ for "non-ascii" input.

Most probably a faulty implementation of MDd5Crypt on the clients side.

Side note: as the algorithm used by phps crypt-function is version and OS dependent, this should also be switched to a fixed algorithm.

**Comment by estralis** [comment]
> > https://illarion.org/mantis/view.php?id=6242 https://illarion.org/mantis/view.php?id=8936
> 
> Access Denied.
> 
> :(

The Mantis tickets describe the same problem/issue, so I linked them here for completeness. Mantis is not used actively for bugtracking anymore but is still a helpful archive of reports/details.

**Comment by Asyxian** [comment]
I found a concrete encoding mismatch between character-list retrieval and the game login. The resulting password hash differences are reproducible.

### Different password bytes in the two login paths

[Login.java](https://github.com/Illarion-eV/Illarion-Java/blob/d71f2c3a883dd1c0cd7d950ecf83e0c78cafb75e/illaclient/src/main/java/illarion/client/Login.java#L253) encodes the password as **UTF-8** for the HTTP character-list request.

For the game login, [LoginCmd](https://github.com/Illarion-eV/Illarion-Java/blob/d71f2c3a883dd1c0cd7d950ecf83e0c78cafb75e/illaclient/src/main/java/illarion/client/net/client/LoginCmd.java#L64-L73) computes the password hash locally using `Md5Crypto`. However, [Md5Crypto.crypt()](https://github.com/Illarion-eV/Illarion-Java/blob/d71f2c3a883dd1c0cd7d950ecf83e0c78cafb75e/illacommon/src/main/java/illarion/common/util/Md5Crypto.java#L70-L92) explicitly converts the password to **ISO-8859-1**.

For example, `ä` becomes:

- UTF-8: `c3 a4`
- ISO-8859-1: `e4`

These different byte sequences produce different hashes. Characters outside ISO-8859-1 are additionally replaced during encoding.

The [public website implementation](https://github.com/Illarion-eV/Illarion-Website/blob/master/website/community/account/xml_charlist.php#L13-L22) applies PHP `crypt()` to the submitted password without converting it to Latin-1, then compares the result with `acc_passwd`. The [examined server implementation](https://github.com/Illarion-eV/Illarion-Server/blob/669a8ec407785fb73aa8bc3be2d724a0ac9fb92d/src/Player.cpp#L884-L902) compares the client-supplied hash directly with that stored value.

This explains the reported sequence: character-list authentication succeeds, but selecting a character causes the client to send a different hash and receive a wrong-password response.

### Changing the encoding alone is insufficient

The two loops in [Md5Crypto.java](https://github.com/Illarion-eV/Illarion-Java/blob/d71f2c3a883dd1c0cd7d950ecf83e0c78cafb75e/illacommon/src/main/java/illarion/common/util/Md5Crypto.java#L86-L92) use `message.length()`. MD5-crypt operates on bytes, so these calculations need `messageBytes.length` when using UTF-8.

Comparisons against OpenSSL MD5-crypt produced:

| Implementation | ASCII control | Six non-ASCII cases |
|---|---|---|
| Current client | Matches | All differ |
| UTF-8 encoding only | Matches | All still differ |
| UTF-8 plus both byte-length corrections | Matches | All match |

The cases cover accented characters, the euro sign, CJK, supplementary characters, and the 16-character/17-byte boundary.

### Possible changes

- Define one consistent password encoding across web and game authentication.
- Use UTF-8 password bytes and byte counts throughout the existing MD5-crypt implementation.
- Add fixed reference vectors covering ASCII and multibyte input.
- Before deployment, check the actual website authentication path and any historical password-encoding differences affecting existing accounts.

The hash mismatch is established in isolated tests. The currently deployed website version and a complete live login were not verified.
