### ISSUE TITLE
mymemory.translated.net does not work

### ISSUE THREAD

**Issue by estralis** [Illarion-eV/Illarion-Java#140]
ERROR - 2023-04-05 16:56:19,443 - [pool-1-thread-2]: Unexpected error while decoding json
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at illarion.client.util.translation.mymemory.MyMemoryProvider.getTranslation(MyMemoryProvider.java:77)
	at illarion.client.util.translation.TranslateSentenceTask.call(TranslateSentenceTask.java:43)
	at illarion.client.util.translation.TranslateSentenceTask.call(TranslateSentenceTask.java:25)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
	... 8 common frames omitted

**Comment by estralis** [comment]
More info here (internal link): https://discord.com/channels/401855954272124940/676112248581652508/1071182740969500815

**Comment by brightrim** [comment]
Fixed this a while back
